config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  
  resources :ideas, only: [:index, :new, :create,:show, :edit, :update, :destroy] do
    resources :reviews, shallow: true, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
    end
  end
  
  resources :users, only: [:new, :create]
  
  resource :session, only: [:new, :create, :destroy]
  
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action(:create, :read, :update, :delete, to: :crud)

    can :crud, Idea do |idea|
      idea.user == user
    end

    can :crud, Review do |review|
      review.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    
    has_many :reviews, dependent: :destroy
    validates :title, presence: true

    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :review_id, uniqueness: {scope: :user_id}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy

    # Validations:
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
    validates :first_name, :last_name, presence: true

    def full_name
      "#{first_name} #{last_name}".strip
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    private
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
  
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    helper_method :current_user
  
    def authenticate_user!
      unless user_signed_in?
        flash[:alert] = 'You must sign in or sign up first!'
        redirect_to new_session_path
      end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]
    
    def index
        @ideas = Idea.order(created_at: :DESC)
    end

    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new(idea_params)
        @idea.user = current_user
        if @idea.save
            redirect_to ideas_path
        else
            render :new
        end
    end

    def show
        @review = Review.new

        @reviews = @idea.reviews.order(created_at: :desc)
       
      
    end

    def edit
    end

    def update
        
        if @idea.update idea_params
            redirect_to ideas_path(@idea)
        else
            render :edit
        end 
    end

    def destroy
        @idea.destroy
        redirect_to ideas_path
    end 

    private

    def idea_params
        params.require(:idea).permit(:title, :description)
    end

    def find_idea
        @idea = Idea.find params[:id]
    end
    def authorize!
        unless can?(:crud, @idea)
            redirect_to root_path, alert: "access denied"
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user

    def create
      like = Like.new
      review = Review.find params[:campaign_id]
      like.review = campaign
      like.user = current_user
      if like.save
        redirect_to review_path(review), notice: "Thanks for liking!"
      else
        redirect_to review_path(review), alert: "Can't like! Liked already?"
      end
    end

    def destroy
        review = Campaign.find params[:campaign_id]
        like = current_user.likes.find params[:id]
        like.destroy
        redirect_to review_path(review), notice: "Like removed!"
      end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_review, only: [:destroy]
  before_action :authorize!, only: [:edit, :update, :destroy]
 

  def create
    @idea = Idea.find(params[:idea_id])
    @review = Review.new review_params
    @review.idea = @idea
    @review.user = current_user
    if @review.save
      redirect_to @idea
    else
      @reviews = @idea.reviews.order(created_at: :desc)
      render 'idea/show'
    end
  end
  def destroy
    @review.destroy
    redirect_to @review.idea
  end

  

  private
  def find_review
    @review = Review.find params[:id]
  end

  def authorize!
    redirect_to root_path, alert: "access denied" unless can? :crud, @review
  end

  def review_params
    params.require(:review).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:email])
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "Thank you for signing in!"
        redirect_to root_path
      else
        flash.now[:alert] = "Wrong email or password!"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Signed out!"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new user_params
        if @user.save
          
          flash[:notice] = "Thank you for signing up!"
          redirect_to root_path
        else
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(
          :first_name, :last_name, :email, :password, :password_confirmation
        )
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_with model: @idea, local: true do |f| %>
  <% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit idea</h1>
<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Index Page</h1>

<% @ideas.each do |idea|%>
<div>
<h4><%= link_to idea.title,  idea_path(idea.id)%></h4>
<br>
<%= idea.description%>
<%= idea.user.id%>
<div>
<hr>
<%end%>

app/views/ideas/new.html.erb
<h1>New Idea<h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p>Description: <%= @idea.description %></p>

  <%= link_to "Edit", edit_idea_path(@idea) %> 

  <%= link_to "Delete", idea_path(@idea), method: :delete, data: { confirm: 'Are you sure that you want to delete ?' } %>

<br>
  

<%= form_with(model: [@idea, @review], local: true) do |f| %>
  <% if @review.errors.present? %>
    <p>
      <%= @review.errors.full_messages.join(', ') %>
    </p>
  <% end %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>



<h3>Reviews</h3>
<%#
  Display all of the reviews for this product
%>
<% @reviews.each do |review| %>

    <p>
      <%= review.body %>
    </p>
    <p>Reviewed by: <%= review.user.full_name %></p>
    <% if can? :crud, review %>
      <%= link_to 'Delete', review_path(review), method: :delete, data: { confirm: 'Are you sure that you want to delete this review?' } %>
      <%= link_to "Like", review_path(review), class: "icon-big", method: :post   %>
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIdeas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav>
  <%= link_to 'Home', root_path%>
  |
  <%= link_to 'New Idea', new_idea_path%>
  |

   <% if user_signed_in? %>
        <span>Hello, <%= current_user.first_name %>!</span>
        |
        <%= link_to 'Sign Out', session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_session_path %>
        |
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
  </nav>
   <% flash.each do |type, message| %>
        <div class="flash-message alert alert-<%= type %>">
          <%= message %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up<h1>

<% if @user.errors.any? %>
<p>
  <%= @user.errors.full_messages.join(', ') %>
</p>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>